# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: brad.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbrad.proto\x12\x04\x62rad\"\x1d\n\tSessionId\x12\x10\n\x08id_value\x18\x01 \x01(\x04\"\x15\n\x13StartSessionRequest\"3\n\x14StartSessionResponse\x12\x1b\n\x02id\x18\x01 \x01(\x0b\x32\x0f.brad.SessionId\"=\n\x0fRunQueryRequest\x12\x1b\n\x02id\x18\x01 \x01(\x0b\x32\x0f.brad.SessionId\x12\r\n\x05query\x18\x02 \x01(\t\"\x87\x01\n\x10RunQueryResponse\x12#\n\x03row\x18\x01 \x01(\x0b\x32\x14.brad.QueryResultRowH\x00\x12!\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x10.brad.QueryErrorH\x00\x12!\n\x0bserviced_by\x18\n \x01(\x0e\x32\x0c.brad.EngineB\x08\n\x06result\"\"\n\x0eQueryResultRow\x12\x10\n\x08row_data\x18\x01 \x01(\x0c\"\x1f\n\nQueryError\x12\x11\n\terror_msg\x18\x01 \x01(\t\"0\n\x11\x45ndSessionRequest\x12\x1b\n\x02id\x18\x01 \x01(\x0b\x32\x0f.brad.SessionId\"\x14\n\x12\x45ndSessionResponse*T\n\x06\x45ngine\x12\x0f\n\x0b\x45NGINE_NONE\x10\x00\x12\x11\n\rENGINE_ATHENA\x10\x01\x12\x11\n\rENGINE_AURORA\x10\x02\x12\x13\n\x0f\x45NGINE_REDSHIFT\x10\x03\x32\xd1\x01\n\x04\x42rad\x12G\n\x0cStartSession\x12\x19.brad.StartSessionRequest\x1a\x1a.brad.StartSessionResponse\"\x00\x12=\n\x08RunQuery\x12\x15.brad.RunQueryRequest\x1a\x16.brad.RunQueryResponse\"\x00\x30\x01\x12\x41\n\nEndSession\x12\x17.brad.EndSessionRequest\x1a\x18.brad.EndSessionResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'brad_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENGINE._serialized_start=469
  _ENGINE._serialized_end=553
  _SESSIONID._serialized_start=20
  _SESSIONID._serialized_end=49
  _STARTSESSIONREQUEST._serialized_start=51
  _STARTSESSIONREQUEST._serialized_end=72
  _STARTSESSIONRESPONSE._serialized_start=74
  _STARTSESSIONRESPONSE._serialized_end=125
  _RUNQUERYREQUEST._serialized_start=127
  _RUNQUERYREQUEST._serialized_end=188
  _RUNQUERYRESPONSE._serialized_start=191
  _RUNQUERYRESPONSE._serialized_end=326
  _QUERYRESULTROW._serialized_start=328
  _QUERYRESULTROW._serialized_end=362
  _QUERYERROR._serialized_start=364
  _QUERYERROR._serialized_end=395
  _ENDSESSIONREQUEST._serialized_start=397
  _ENDSESSIONREQUEST._serialized_end=445
  _ENDSESSIONRESPONSE._serialized_start=447
  _ENDSESSIONRESPONSE._serialized_end=467
  _BRAD._serialized_start=556
  _BRAD._serialized_end=765
# @@protoc_insertion_point(module_scope)
