# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interface/schema.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16interface/schema.proto\x12\x04vdbe\"9\n\x05Table\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\"\n\x07\x63olumns\x18\x02 \x03(\x0b\x32\x11.vdbe.TableColumn\"K\n\x0bTableColumn\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1c\n\x04type\x18\x02 \x01(\x0e\x32\x0e.vdbe.DataType\x12\x10\n\x08nullable\x18\x03 \x01(\x08*G\n\x08\x44\x61taType\x12\x0e\n\nDT_UNKNOWN\x10\x00\x12\r\n\tDT_INT_32\x10\x01\x12\r\n\tDT_INT_64\x10\x02\x12\r\n\tDT_STRING\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interface.schema_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DATATYPE']._serialized_start=168
  _globals['_DATATYPE']._serialized_end=239
  _globals['_TABLE']._serialized_start=32
  _globals['_TABLE']._serialized_end=89
  _globals['_TABLECOLUMN']._serialized_start=91
  _globals['_TABLECOLUMN']._serialized_end=166
# @@protoc_insertion_point(module_scope)
