# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interface/vdbe.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14interface/vdbe.proto\x12\x04vdbe\"}\n\rVirtualEngine\x12\x0c\n\x04name\x18\x01 \x01(\t\x12 \n\x02qi\x18\x02 \x01(\x0e\x32\x14.vdbe.QueryInterface\x12\"\n\x06tables\x18\x03 \x03(\x0b\x32\x12.vdbe.VirtualTable\x12\x18\n\x10max_staleness_ms\x18\x04 \x01(\x04\".\n\x0cVirtualTable\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08writable\x18\x02 \x01(\x08*{\n\x0eQueryInterface\x12\x0e\n\nQI_UNKNOWN\x10\x00\x12\x15\n\x11QI_SQL_POSTGRESQL\x10\x65\x12\x10\n\x0cQI_SQL_MYSQL\x10\x66\x12\x18\n\x13QI_SQL_AWS_REDSHIFT\x10\xc9\x01\x12\x16\n\x11QI_SQL_AWS_ATHENA\x10\xca\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interface.vdbe_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_QUERYINTERFACE']._serialized_start=205
  _globals['_QUERYINTERFACE']._serialized_end=328
  _globals['_VIRTUALENGINE']._serialized_start=30
  _globals['_VIRTUALENGINE']._serialized_end=155
  _globals['_VIRTUALTABLE']._serialized_start=157
  _globals['_VIRTUALTABLE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
