schema_name: test_schema

# Use PostgreSQL data types. Make sure the data type is supported in Athena too.
tables:
  - table_name: demo_new
    columns:
      - name: id
        data_type: BIGINT
        primary_key: true
      - name: db
        data_type: TEXT
      - name: value
        data_type: BIGINT

provisioning:
  aurora:
    instance_type: db.r6g.large
    num_nodes: 1

  redshift:
    instance_type: dc2.large
    num_nodes: 1
