schema_name: tpch

# Use PostgreSQL data types. Make sure the data type is supported in Athena too.
tables:
  - table_name: part
    columns:
      - name: p_partkey
        type: INTEGER
        primary_key: true
      - name: p_name
        type: VARCHAR(55)
      - name: p_mfgr
        type: CHAR(25)
      - name: p_brand
        type: CHAR(10)
      - name: p_type
        type: VARCHAR(25)
      - name: p_size
        type: INTEGER
      - name: p_container
        type: CHAR(10)
      - name: p_retailprice
        type: DECIMAL
      - name: p_comment
        type: VARCHAR(23)
      - name: p_extra
        type: CHAR(1)

  - table_name: supplier
    columns:
      - name: s_suppkey
        type: INTEGER
        primary_key: true
      - name: s_name
        type: CHAR(25)
      - name: s_address
        type: VARCHAR(40)
      - name: s_nationkey
        type: BIGINT
      - name: s_phone
        type: CHAR(15)
      - name: s_acctbal
        type: DECIMAL
      - name: s_comment
        type: VARCHAR(101)
      - name: s_extra
        type: CHAR(1)

  - table_name: partsupp
    columns:
      - name: ps_partkey
        type: BIGINT
        primary_key: true
      - name: ps_suppkey
        type: BIGINT
        primary_key: true
      - name: ps_availqty
        type: INTEGER
      - name: ps_supplycost
        type: DECIMAL
      - name: ps_comment
        type: VARCHAR(199)
      - name: ps_extra
        type: CHAR(1)

  - table_name: customer
    columns:
      - name: c_custkey
        type: INTEGER
        primary_key: true
      - name: c_name
        type: VARCHAR(25)
      - name: c_address
        type: VARCHAR(40)
      - name: c_nationkey
        type: BIGINT
      - name: c_phone
        type: CHAR(15)
      - name: c_acctbal
        type: DECIMAL
      - name: c_mktsegment
        type: CHAR(10)
      - name: c_comment
        type: VARCHAR(117)
      - name: c_extra
        type: CHAR(1)

  - table_name: orders
    columns:
      - name: o_orderkey
        type: INTEGER
        primary_key: true
      - name: o_custkey
        type: BIGINT
      - name: o_orderstatus
        type: CHAR(1)
      - name: o_totalprice
        type: DECIMAL
      - name: o_orderdate
        type: DATE
      - name: o_orderpriority
        type: CHAR(15)
      - name: o_clerk
        type: CHAR(15)
      - name: o_shippriority
        type: INTEGER
      - name: o_comment
        type: VARCHAR(79)
      - name: o_extra
        type: CHAR(1)

  - table_name: lineitem
    columns:
      - name: l_orderkey
        type: BIGINT
        primary_key: true
      - name: l_partkey
        type: BIGINT
      - name: l_suppkey
        type: BIGINT
      - name: l_linenumber
        type: INTEGER
        primary_key: true
      - name: l_quantity
        type: DECIMAL
      - name: l_extendedprice
        type:	DECIMAL
      - name: l_discount
        type: DECIMAL
      - name: l_tax
        type: DECIMAL
      - name: l_returnflag
        type: CHAR(1)
      - name: l_linestatus
        type: CHAR(1)
      - name: l_shipdate
        type: DATE
      - name: l_commitdate
        type: DATE
      - name: l_receiptdate
        type: DATE
      - name: l_shipinstruct
      	type: CHAR(25)
      - name: l_shipmode
        type: CHAR(10)
      - name: l_comment
        type: VARCHAR(44)
      - name: l_extra
        type: CHAR(1)

  - table_name: nation
    columns:
      - name: n_nationkey
        type: INTEGER
        primary_key: true
      - name: n_name
        type: CHAR(25)
      - name: n_regionkey
        type: BIGINT
      - name: n_comment
        type: VARCHAR(152)
      - name: n_extra
        type: CHAR(1)

  - table_name: region
    columns:
      - name: r_regionkey
        type: INTEGER
        primary_key: true
      - name: r_name
        type: CHAR(25)
      - name: r_comment
        type: VARCHAR(152)
      - name: r_extra
        type: CHAR(1)