schema_name: tpch

# Use PostgreSQL data types. Make sure the data type is supported in Athena too.
tables:
  - table_name: part
    columns:
      - name: p_partkey
        data_type: INT
        primary_key: true
      - name: p_name
        data_type: TEXT
      - name: p_mfgr
        data_type: TEXT
      - name: p_brand
        data_type: TEXT
      - name: p_type
        data_type: TEXT
      - name: p_size
        data_type: INT
      - name: p_container
        data_type: TEXT
      - name: p_retailprice
        data_type: DECIMAL(10)
      - name: p_comment
        data_type: TEXT
      - name: p_extra
        data_type: TEXT

  - table_name: supplier
    columns:
      - name: s_suppkey
        data_type: INT
        primary_key: true
      - name: s_name
        data_type: TEXT
      - name: s_address
        data_type: TEXT
      - name: s_nationkey
        data_type: BIGINT
      - name: s_phone
        data_type: TEXT
      - name: s_acctbal
        data_type: DECIMAL(10)
      - name: s_comment
        data_type: TEXT
      - name: s_extra
        data_type: TEXT

  - table_name: partsupp
    columns:
      - name: ps_partkey
        data_type: BIGINT
        primary_key: true
      - name: ps_suppkey
        data_type: BIGINT
        primary_key: true
      - name: ps_availqty
        data_type: INT
      - name: ps_supplycost
        data_type: DECIMAL(10)
      - name: ps_comment
        data_type: TEXT
      - name: ps_extra
        data_type: TEXT

  - table_name: customer
    columns:
      - name: c_custkey
        data_type: INT
        primary_key: true
      - name: c_name
        data_type: TEXT
      - name: c_address
        data_type: TEXT
      - name: c_nationkey
        data_type: BIGINT
      - name: c_phone
        data_type: TEXT
      - name: c_acctbal
        data_type: DECIMAL(10)
      - name: c_mktsegment
        data_type: TEXT
      - name: c_comment
        data_type: TEXT
      - name: c_extra
        data_type: TEXT

  - table_name: orders
    columns:
      - name: o_orderkey
        data_type: INT
        primary_key: true
      - name: o_custkey
        data_type: BIGINT
      - name: o_orderstatus
        data_type: TEXT
      - name: o_totalprice
        data_type: DECIMAL(10)
      - name: o_orderdate
        data_type: DATE
      - name: o_orderpriority
        data_type: TEXT
      - name: o_clerk
        data_type: TEXT
      - name: o_shippriority
        data_type: INT
      - name: o_comment
        data_type: TEXT
      - name: o_extra
        data_type: TEXT

  - table_name: lineitem
    columns:
      - name: l_orderkey
        data_type: BIGINT
        primary_key: true
      - name: l_partkey
        data_type: BIGINT
      - name: l_suppkey
        data_type: BIGINT
      - name: l_linenumber
        data_type: INT
        primary_key: true
      - name: l_quantity
        data_type: DECIMAL(10)
      - name: l_extendedprice
        data_type: DECIMAL(10)
      - name: l_discount
        data_type: DECIMAL(10)
      - name: l_tax
        data_type: DECIMAL(10)
      - name: l_returnflag
        data_type: TEXT
      - name: l_linestatus
        data_type: TEXT
      - name: l_shipdate
        data_type: DATE
      - name: l_commitdate
        data_type: DATE
      - name: l_receiptdate
        data_type: DATE
      - name: l_shipinstruct
        data_type: TEXT
      - name: l_shipmode
        data_type: TEXT
      - name: l_comment
        data_type: TEXT
      - name: l_extra
        data_type: TEXT

  - table_name: nation
    columns:
      - name: n_nationkey
        data_type: INT
        primary_key: true
      - name: n_name
        data_type: TEXT
      - name: n_regionkey
        data_type: BIGINT
      - name: n_comment
        data_type: TEXT
      - name: n_extra
        data_type: TEXT

  - table_name: region
    columns:
      - name: r_regionkey
        data_type: INT
        primary_key: true
      - name: r_name
        data_type: TEXT
      - name: r_comment
        data_type: TEXT
      - name: r_extra
        data_type: TEXT
