// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: brad.proto
#ifndef GRPC_brad_2eproto__INCLUDED
#define GRPC_brad_2eproto__INCLUDED

#include "brad.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace brad {

// BRAD's internal-use RPC interface.
class Brad final {
 public:
  static constexpr char const* service_full_name() {
    return "brad.Brad";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Start a new session.
    // All requests (except this one) must include a `SessionId` that is returned
    // by this method.
    virtual ::grpc::Status StartSession(::grpc::ClientContext* context, const ::brad::StartSessionRequest& request, ::brad::StartSessionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::brad::StartSessionResponse>> AsyncStartSession(::grpc::ClientContext* context, const ::brad::StartSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::brad::StartSessionResponse>>(AsyncStartSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::brad::StartSessionResponse>> PrepareAsyncStartSession(::grpc::ClientContext* context, const ::brad::StartSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::brad::StartSessionResponse>>(PrepareAsyncStartSessionRaw(context, request, cq));
    }
    // Run a SQL query (or execute an internal command like BRAD_SYNC).
    std::unique_ptr< ::grpc::ClientReaderInterface< ::brad::RunQueryResponse>> RunQuery(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::brad::RunQueryResponse>>(RunQueryRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::brad::RunQueryResponse>> AsyncRunQuery(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::brad::RunQueryResponse>>(AsyncRunQueryRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::brad::RunQueryResponse>> PrepareAsyncRunQuery(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::brad::RunQueryResponse>>(PrepareAsyncRunQueryRaw(context, request, cq));
    }
    // Run a SQL query (or execute an internal command like BRAD_SYNC) and return
    // the results as a serialized JSON string.
    virtual ::grpc::Status RunQueryJson(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request, ::brad::RunQueryJsonResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::brad::RunQueryJsonResponse>> AsyncRunQueryJson(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::brad::RunQueryJsonResponse>>(AsyncRunQueryJsonRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::brad::RunQueryJsonResponse>> PrepareAsyncRunQueryJson(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::brad::RunQueryJsonResponse>>(PrepareAsyncRunQueryJsonRaw(context, request, cq));
    }
    // End a previously started session. Clients must call this method once they
    // are done with their session.
    virtual ::grpc::Status EndSession(::grpc::ClientContext* context, const ::brad::EndSessionRequest& request, ::brad::EndSessionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::brad::EndSessionResponse>> AsyncEndSession(::grpc::ClientContext* context, const ::brad::EndSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::brad::EndSessionResponse>>(AsyncEndSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::brad::EndSessionResponse>> PrepareAsyncEndSession(::grpc::ClientContext* context, const ::brad::EndSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::brad::EndSessionResponse>>(PrepareAsyncEndSessionRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Start a new session.
      // All requests (except this one) must include a `SessionId` that is returned
      // by this method.
      virtual void StartSession(::grpc::ClientContext* context, const ::brad::StartSessionRequest* request, ::brad::StartSessionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void StartSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::StartSessionResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void StartSession(::grpc::ClientContext* context, const ::brad::StartSessionRequest* request, ::brad::StartSessionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void StartSession(::grpc::ClientContext* context, const ::brad::StartSessionRequest* request, ::brad::StartSessionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void StartSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::StartSessionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void StartSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::StartSessionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // Run a SQL query (or execute an internal command like BRAD_SYNC).
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void RunQuery(::grpc::ClientContext* context, ::brad::RunQueryRequest* request, ::grpc::ClientReadReactor< ::brad::RunQueryResponse>* reactor) = 0;
      #else
      virtual void RunQuery(::grpc::ClientContext* context, ::brad::RunQueryRequest* request, ::grpc::experimental::ClientReadReactor< ::brad::RunQueryResponse>* reactor) = 0;
      #endif
      // Run a SQL query (or execute an internal command like BRAD_SYNC) and return
      // the results as a serialized JSON string.
      virtual void RunQueryJson(::grpc::ClientContext* context, const ::brad::RunQueryRequest* request, ::brad::RunQueryJsonResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RunQueryJson(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::RunQueryJsonResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void RunQueryJson(::grpc::ClientContext* context, const ::brad::RunQueryRequest* request, ::brad::RunQueryJsonResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void RunQueryJson(::grpc::ClientContext* context, const ::brad::RunQueryRequest* request, ::brad::RunQueryJsonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void RunQueryJson(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::RunQueryJsonResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void RunQueryJson(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::RunQueryJsonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // End a previously started session. Clients must call this method once they
      // are done with their session.
      virtual void EndSession(::grpc::ClientContext* context, const ::brad::EndSessionRequest* request, ::brad::EndSessionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void EndSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::EndSessionResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void EndSession(::grpc::ClientContext* context, const ::brad::EndSessionRequest* request, ::brad::EndSessionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void EndSession(::grpc::ClientContext* context, const ::brad::EndSessionRequest* request, ::brad::EndSessionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void EndSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::EndSessionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void EndSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::EndSessionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::brad::StartSessionResponse>* AsyncStartSessionRaw(::grpc::ClientContext* context, const ::brad::StartSessionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::brad::StartSessionResponse>* PrepareAsyncStartSessionRaw(::grpc::ClientContext* context, const ::brad::StartSessionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::brad::RunQueryResponse>* RunQueryRaw(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::brad::RunQueryResponse>* AsyncRunQueryRaw(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::brad::RunQueryResponse>* PrepareAsyncRunQueryRaw(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::brad::RunQueryJsonResponse>* AsyncRunQueryJsonRaw(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::brad::RunQueryJsonResponse>* PrepareAsyncRunQueryJsonRaw(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::brad::EndSessionResponse>* AsyncEndSessionRaw(::grpc::ClientContext* context, const ::brad::EndSessionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::brad::EndSessionResponse>* PrepareAsyncEndSessionRaw(::grpc::ClientContext* context, const ::brad::EndSessionRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status StartSession(::grpc::ClientContext* context, const ::brad::StartSessionRequest& request, ::brad::StartSessionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::brad::StartSessionResponse>> AsyncStartSession(::grpc::ClientContext* context, const ::brad::StartSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::brad::StartSessionResponse>>(AsyncStartSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::brad::StartSessionResponse>> PrepareAsyncStartSession(::grpc::ClientContext* context, const ::brad::StartSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::brad::StartSessionResponse>>(PrepareAsyncStartSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::brad::RunQueryResponse>> RunQuery(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::brad::RunQueryResponse>>(RunQueryRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::brad::RunQueryResponse>> AsyncRunQuery(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::brad::RunQueryResponse>>(AsyncRunQueryRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::brad::RunQueryResponse>> PrepareAsyncRunQuery(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::brad::RunQueryResponse>>(PrepareAsyncRunQueryRaw(context, request, cq));
    }
    ::grpc::Status RunQueryJson(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request, ::brad::RunQueryJsonResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::brad::RunQueryJsonResponse>> AsyncRunQueryJson(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::brad::RunQueryJsonResponse>>(AsyncRunQueryJsonRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::brad::RunQueryJsonResponse>> PrepareAsyncRunQueryJson(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::brad::RunQueryJsonResponse>>(PrepareAsyncRunQueryJsonRaw(context, request, cq));
    }
    ::grpc::Status EndSession(::grpc::ClientContext* context, const ::brad::EndSessionRequest& request, ::brad::EndSessionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::brad::EndSessionResponse>> AsyncEndSession(::grpc::ClientContext* context, const ::brad::EndSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::brad::EndSessionResponse>>(AsyncEndSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::brad::EndSessionResponse>> PrepareAsyncEndSession(::grpc::ClientContext* context, const ::brad::EndSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::brad::EndSessionResponse>>(PrepareAsyncEndSessionRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void StartSession(::grpc::ClientContext* context, const ::brad::StartSessionRequest* request, ::brad::StartSessionResponse* response, std::function<void(::grpc::Status)>) override;
      void StartSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::StartSessionResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void StartSession(::grpc::ClientContext* context, const ::brad::StartSessionRequest* request, ::brad::StartSessionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void StartSession(::grpc::ClientContext* context, const ::brad::StartSessionRequest* request, ::brad::StartSessionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void StartSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::StartSessionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void StartSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::StartSessionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void RunQuery(::grpc::ClientContext* context, ::brad::RunQueryRequest* request, ::grpc::ClientReadReactor< ::brad::RunQueryResponse>* reactor) override;
      #else
      void RunQuery(::grpc::ClientContext* context, ::brad::RunQueryRequest* request, ::grpc::experimental::ClientReadReactor< ::brad::RunQueryResponse>* reactor) override;
      #endif
      void RunQueryJson(::grpc::ClientContext* context, const ::brad::RunQueryRequest* request, ::brad::RunQueryJsonResponse* response, std::function<void(::grpc::Status)>) override;
      void RunQueryJson(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::RunQueryJsonResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void RunQueryJson(::grpc::ClientContext* context, const ::brad::RunQueryRequest* request, ::brad::RunQueryJsonResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void RunQueryJson(::grpc::ClientContext* context, const ::brad::RunQueryRequest* request, ::brad::RunQueryJsonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void RunQueryJson(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::RunQueryJsonResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void RunQueryJson(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::RunQueryJsonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void EndSession(::grpc::ClientContext* context, const ::brad::EndSessionRequest* request, ::brad::EndSessionResponse* response, std::function<void(::grpc::Status)>) override;
      void EndSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::EndSessionResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void EndSession(::grpc::ClientContext* context, const ::brad::EndSessionRequest* request, ::brad::EndSessionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void EndSession(::grpc::ClientContext* context, const ::brad::EndSessionRequest* request, ::brad::EndSessionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void EndSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::EndSessionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void EndSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::EndSessionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::brad::StartSessionResponse>* AsyncStartSessionRaw(::grpc::ClientContext* context, const ::brad::StartSessionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::brad::StartSessionResponse>* PrepareAsyncStartSessionRaw(::grpc::ClientContext* context, const ::brad::StartSessionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::brad::RunQueryResponse>* RunQueryRaw(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request) override;
    ::grpc::ClientAsyncReader< ::brad::RunQueryResponse>* AsyncRunQueryRaw(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::brad::RunQueryResponse>* PrepareAsyncRunQueryRaw(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::brad::RunQueryJsonResponse>* AsyncRunQueryJsonRaw(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::brad::RunQueryJsonResponse>* PrepareAsyncRunQueryJsonRaw(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::brad::EndSessionResponse>* AsyncEndSessionRaw(::grpc::ClientContext* context, const ::brad::EndSessionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::brad::EndSessionResponse>* PrepareAsyncEndSessionRaw(::grpc::ClientContext* context, const ::brad::EndSessionRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StartSession_;
    const ::grpc::internal::RpcMethod rpcmethod_RunQuery_;
    const ::grpc::internal::RpcMethod rpcmethod_RunQueryJson_;
    const ::grpc::internal::RpcMethod rpcmethod_EndSession_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Start a new session.
    // All requests (except this one) must include a `SessionId` that is returned
    // by this method.
    virtual ::grpc::Status StartSession(::grpc::ServerContext* context, const ::brad::StartSessionRequest* request, ::brad::StartSessionResponse* response);
    // Run a SQL query (or execute an internal command like BRAD_SYNC).
    virtual ::grpc::Status RunQuery(::grpc::ServerContext* context, const ::brad::RunQueryRequest* request, ::grpc::ServerWriter< ::brad::RunQueryResponse>* writer);
    // Run a SQL query (or execute an internal command like BRAD_SYNC) and return
    // the results as a serialized JSON string.
    virtual ::grpc::Status RunQueryJson(::grpc::ServerContext* context, const ::brad::RunQueryRequest* request, ::brad::RunQueryJsonResponse* response);
    // End a previously started session. Clients must call this method once they
    // are done with their session.
    virtual ::grpc::Status EndSession(::grpc::ServerContext* context, const ::brad::EndSessionRequest* request, ::brad::EndSessionResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_StartSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StartSession() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StartSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartSession(::grpc::ServerContext* /*context*/, const ::brad::StartSessionRequest* /*request*/, ::brad::StartSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStartSession(::grpc::ServerContext* context, ::brad::StartSessionRequest* request, ::grpc::ServerAsyncResponseWriter< ::brad::StartSessionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RunQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RunQuery() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_RunQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunQuery(::grpc::ServerContext* /*context*/, const ::brad::RunQueryRequest* /*request*/, ::grpc::ServerWriter< ::brad::RunQueryResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRunQuery(::grpc::ServerContext* context, ::brad::RunQueryRequest* request, ::grpc::ServerAsyncWriter< ::brad::RunQueryResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RunQueryJson : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RunQueryJson() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_RunQueryJson() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunQueryJson(::grpc::ServerContext* /*context*/, const ::brad::RunQueryRequest* /*request*/, ::brad::RunQueryJsonResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRunQueryJson(::grpc::ServerContext* context, ::brad::RunQueryRequest* request, ::grpc::ServerAsyncResponseWriter< ::brad::RunQueryJsonResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_EndSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_EndSession() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_EndSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EndSession(::grpc::ServerContext* /*context*/, const ::brad::EndSessionRequest* /*request*/, ::brad::EndSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEndSession(::grpc::ServerContext* context, ::brad::EndSessionRequest* request, ::grpc::ServerAsyncResponseWriter< ::brad::EndSessionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StartSession<WithAsyncMethod_RunQuery<WithAsyncMethod_RunQueryJson<WithAsyncMethod_EndSession<Service > > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_StartSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_StartSession() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::brad::StartSessionRequest, ::brad::StartSessionResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::brad::StartSessionRequest* request, ::brad::StartSessionResponse* response) { return this->StartSession(context, request, response); }));}
    void SetMessageAllocatorFor_StartSession(
        ::grpc::experimental::MessageAllocator< ::brad::StartSessionRequest, ::brad::StartSessionResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::brad::StartSessionRequest, ::brad::StartSessionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_StartSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartSession(::grpc::ServerContext* /*context*/, const ::brad::StartSessionRequest* /*request*/, ::brad::StartSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* StartSession(
      ::grpc::CallbackServerContext* /*context*/, const ::brad::StartSessionRequest* /*request*/, ::brad::StartSessionResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* StartSession(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::brad::StartSessionRequest* /*request*/, ::brad::StartSessionResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_RunQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_RunQuery() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackServerStreamingHandler< ::brad::RunQueryRequest, ::brad::RunQueryResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::brad::RunQueryRequest* request) { return this->RunQuery(context, request); }));
    }
    ~ExperimentalWithCallbackMethod_RunQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunQuery(::grpc::ServerContext* /*context*/, const ::brad::RunQueryRequest* /*request*/, ::grpc::ServerWriter< ::brad::RunQueryResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::brad::RunQueryResponse>* RunQuery(
      ::grpc::CallbackServerContext* /*context*/, const ::brad::RunQueryRequest* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::brad::RunQueryResponse>* RunQuery(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::brad::RunQueryRequest* /*request*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_RunQueryJson : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_RunQueryJson() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(2,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::brad::RunQueryRequest, ::brad::RunQueryJsonResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::brad::RunQueryRequest* request, ::brad::RunQueryJsonResponse* response) { return this->RunQueryJson(context, request, response); }));}
    void SetMessageAllocatorFor_RunQueryJson(
        ::grpc::experimental::MessageAllocator< ::brad::RunQueryRequest, ::brad::RunQueryJsonResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(2);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::brad::RunQueryRequest, ::brad::RunQueryJsonResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_RunQueryJson() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunQueryJson(::grpc::ServerContext* /*context*/, const ::brad::RunQueryRequest* /*request*/, ::brad::RunQueryJsonResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* RunQueryJson(
      ::grpc::CallbackServerContext* /*context*/, const ::brad::RunQueryRequest* /*request*/, ::brad::RunQueryJsonResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* RunQueryJson(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::brad::RunQueryRequest* /*request*/, ::brad::RunQueryJsonResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_EndSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_EndSession() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(3,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::brad::EndSessionRequest, ::brad::EndSessionResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::brad::EndSessionRequest* request, ::brad::EndSessionResponse* response) { return this->EndSession(context, request, response); }));}
    void SetMessageAllocatorFor_EndSession(
        ::grpc::experimental::MessageAllocator< ::brad::EndSessionRequest, ::brad::EndSessionResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(3);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::brad::EndSessionRequest, ::brad::EndSessionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_EndSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EndSession(::grpc::ServerContext* /*context*/, const ::brad::EndSessionRequest* /*request*/, ::brad::EndSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* EndSession(
      ::grpc::CallbackServerContext* /*context*/, const ::brad::EndSessionRequest* /*request*/, ::brad::EndSessionResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* EndSession(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::brad::EndSessionRequest* /*request*/, ::brad::EndSessionResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_StartSession<ExperimentalWithCallbackMethod_RunQuery<ExperimentalWithCallbackMethod_RunQueryJson<ExperimentalWithCallbackMethod_EndSession<Service > > > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_StartSession<ExperimentalWithCallbackMethod_RunQuery<ExperimentalWithCallbackMethod_RunQueryJson<ExperimentalWithCallbackMethod_EndSession<Service > > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StartSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StartSession() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StartSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartSession(::grpc::ServerContext* /*context*/, const ::brad::StartSessionRequest* /*request*/, ::brad::StartSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RunQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RunQuery() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_RunQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunQuery(::grpc::ServerContext* /*context*/, const ::brad::RunQueryRequest* /*request*/, ::grpc::ServerWriter< ::brad::RunQueryResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RunQueryJson : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RunQueryJson() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_RunQueryJson() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunQueryJson(::grpc::ServerContext* /*context*/, const ::brad::RunQueryRequest* /*request*/, ::brad::RunQueryJsonResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_EndSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_EndSession() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_EndSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EndSession(::grpc::ServerContext* /*context*/, const ::brad::EndSessionRequest* /*request*/, ::brad::EndSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StartSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StartSession() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StartSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartSession(::grpc::ServerContext* /*context*/, const ::brad::StartSessionRequest* /*request*/, ::brad::StartSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStartSession(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RunQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RunQuery() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_RunQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunQuery(::grpc::ServerContext* /*context*/, const ::brad::RunQueryRequest* /*request*/, ::grpc::ServerWriter< ::brad::RunQueryResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRunQuery(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RunQueryJson : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RunQueryJson() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_RunQueryJson() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunQueryJson(::grpc::ServerContext* /*context*/, const ::brad::RunQueryRequest* /*request*/, ::brad::RunQueryJsonResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRunQueryJson(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_EndSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_EndSession() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_EndSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EndSession(::grpc::ServerContext* /*context*/, const ::brad::EndSessionRequest* /*request*/, ::brad::EndSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEndSession(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_StartSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_StartSession() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->StartSession(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_StartSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartSession(::grpc::ServerContext* /*context*/, const ::brad::StartSessionRequest* /*request*/, ::brad::StartSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* StartSession(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* StartSession(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_RunQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_RunQuery() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const::grpc::ByteBuffer* request) { return this->RunQuery(context, request); }));
    }
    ~ExperimentalWithRawCallbackMethod_RunQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunQuery(::grpc::ServerContext* /*context*/, const ::brad::RunQueryRequest* /*request*/, ::grpc::ServerWriter< ::brad::RunQueryResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* RunQuery(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::grpc::ByteBuffer>* RunQuery(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_RunQueryJson : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_RunQueryJson() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(2,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RunQueryJson(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_RunQueryJson() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunQueryJson(::grpc::ServerContext* /*context*/, const ::brad::RunQueryRequest* /*request*/, ::brad::RunQueryJsonResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* RunQueryJson(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* RunQueryJson(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_EndSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_EndSession() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(3,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->EndSession(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_EndSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EndSession(::grpc::ServerContext* /*context*/, const ::brad::EndSessionRequest* /*request*/, ::brad::EndSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* EndSession(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* EndSession(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_StartSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_StartSession() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::brad::StartSessionRequest, ::brad::StartSessionResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::brad::StartSessionRequest, ::brad::StartSessionResponse>* streamer) {
                       return this->StreamedStartSession(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_StartSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StartSession(::grpc::ServerContext* /*context*/, const ::brad::StartSessionRequest* /*request*/, ::brad::StartSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStartSession(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::brad::StartSessionRequest,::brad::StartSessionResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RunQueryJson : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RunQueryJson() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::brad::RunQueryRequest, ::brad::RunQueryJsonResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::brad::RunQueryRequest, ::brad::RunQueryJsonResponse>* streamer) {
                       return this->StreamedRunQueryJson(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RunQueryJson() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RunQueryJson(::grpc::ServerContext* /*context*/, const ::brad::RunQueryRequest* /*request*/, ::brad::RunQueryJsonResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRunQueryJson(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::brad::RunQueryRequest,::brad::RunQueryJsonResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_EndSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_EndSession() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::brad::EndSessionRequest, ::brad::EndSessionResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::brad::EndSessionRequest, ::brad::EndSessionResponse>* streamer) {
                       return this->StreamedEndSession(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_EndSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status EndSession(::grpc::ServerContext* /*context*/, const ::brad::EndSessionRequest* /*request*/, ::brad::EndSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedEndSession(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::brad::EndSessionRequest,::brad::EndSessionResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_StartSession<WithStreamedUnaryMethod_RunQueryJson<WithStreamedUnaryMethod_EndSession<Service > > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_RunQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_RunQuery() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::brad::RunQueryRequest, ::brad::RunQueryResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerSplitStreamer<
                     ::brad::RunQueryRequest, ::brad::RunQueryResponse>* streamer) {
                       return this->StreamedRunQuery(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_RunQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RunQuery(::grpc::ServerContext* /*context*/, const ::brad::RunQueryRequest* /*request*/, ::grpc::ServerWriter< ::brad::RunQueryResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedRunQuery(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::brad::RunQueryRequest,::brad::RunQueryResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_RunQuery<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_StartSession<WithSplitStreamingMethod_RunQuery<WithStreamedUnaryMethod_RunQueryJson<WithStreamedUnaryMethod_EndSession<Service > > > > StreamedService;
};

}  // namespace brad


#endif  // GRPC_brad_2eproto__INCLUDED
