// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: brad.proto

#include "brad.pb.h"
#include "brad.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace brad {

static const char* Brad_method_names[] = {
  "/brad.Brad/StartSession",
  "/brad.Brad/RunQuery",
  "/brad.Brad/RunQueryJson",
  "/brad.Brad/EndSession",
};

std::unique_ptr< Brad::Stub> Brad::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Brad::Stub> stub(new Brad::Stub(channel));
  return stub;
}

Brad::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_StartSession_(Brad_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RunQuery_(Brad_method_names[1], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_RunQueryJson_(Brad_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_EndSession_(Brad_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Brad::Stub::StartSession(::grpc::ClientContext* context, const ::brad::StartSessionRequest& request, ::brad::StartSessionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_StartSession_, context, request, response);
}

void Brad::Stub::experimental_async::StartSession(::grpc::ClientContext* context, const ::brad::StartSessionRequest* request, ::brad::StartSessionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_StartSession_, context, request, response, std::move(f));
}

void Brad::Stub::experimental_async::StartSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::StartSessionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_StartSession_, context, request, response, std::move(f));
}

void Brad::Stub::experimental_async::StartSession(::grpc::ClientContext* context, const ::brad::StartSessionRequest* request, ::brad::StartSessionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_StartSession_, context, request, response, reactor);
}

void Brad::Stub::experimental_async::StartSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::StartSessionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_StartSession_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::brad::StartSessionResponse>* Brad::Stub::AsyncStartSessionRaw(::grpc::ClientContext* context, const ::brad::StartSessionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::brad::StartSessionResponse>::Create(channel_.get(), cq, rpcmethod_StartSession_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::brad::StartSessionResponse>* Brad::Stub::PrepareAsyncStartSessionRaw(::grpc::ClientContext* context, const ::brad::StartSessionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::brad::StartSessionResponse>::Create(channel_.get(), cq, rpcmethod_StartSession_, context, request, false);
}

::grpc::ClientReader< ::brad::RunQueryResponse>* Brad::Stub::RunQueryRaw(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request) {
  return ::grpc_impl::internal::ClientReaderFactory< ::brad::RunQueryResponse>::Create(channel_.get(), rpcmethod_RunQuery_, context, request);
}

void Brad::Stub::experimental_async::RunQuery(::grpc::ClientContext* context, ::brad::RunQueryRequest* request, ::grpc::experimental::ClientReadReactor< ::brad::RunQueryResponse>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderFactory< ::brad::RunQueryResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_RunQuery_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::brad::RunQueryResponse>* Brad::Stub::AsyncRunQueryRaw(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::brad::RunQueryResponse>::Create(channel_.get(), cq, rpcmethod_RunQuery_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::brad::RunQueryResponse>* Brad::Stub::PrepareAsyncRunQueryRaw(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::brad::RunQueryResponse>::Create(channel_.get(), cq, rpcmethod_RunQuery_, context, request, false, nullptr);
}

::grpc::Status Brad::Stub::RunQueryJson(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request, ::brad::RunQueryJsonResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_RunQueryJson_, context, request, response);
}

void Brad::Stub::experimental_async::RunQueryJson(::grpc::ClientContext* context, const ::brad::RunQueryRequest* request, ::brad::RunQueryJsonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_RunQueryJson_, context, request, response, std::move(f));
}

void Brad::Stub::experimental_async::RunQueryJson(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::RunQueryJsonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_RunQueryJson_, context, request, response, std::move(f));
}

void Brad::Stub::experimental_async::RunQueryJson(::grpc::ClientContext* context, const ::brad::RunQueryRequest* request, ::brad::RunQueryJsonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_RunQueryJson_, context, request, response, reactor);
}

void Brad::Stub::experimental_async::RunQueryJson(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::RunQueryJsonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_RunQueryJson_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::brad::RunQueryJsonResponse>* Brad::Stub::AsyncRunQueryJsonRaw(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::brad::RunQueryJsonResponse>::Create(channel_.get(), cq, rpcmethod_RunQueryJson_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::brad::RunQueryJsonResponse>* Brad::Stub::PrepareAsyncRunQueryJsonRaw(::grpc::ClientContext* context, const ::brad::RunQueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::brad::RunQueryJsonResponse>::Create(channel_.get(), cq, rpcmethod_RunQueryJson_, context, request, false);
}

::grpc::Status Brad::Stub::EndSession(::grpc::ClientContext* context, const ::brad::EndSessionRequest& request, ::brad::EndSessionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_EndSession_, context, request, response);
}

void Brad::Stub::experimental_async::EndSession(::grpc::ClientContext* context, const ::brad::EndSessionRequest* request, ::brad::EndSessionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_EndSession_, context, request, response, std::move(f));
}

void Brad::Stub::experimental_async::EndSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::EndSessionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_EndSession_, context, request, response, std::move(f));
}

void Brad::Stub::experimental_async::EndSession(::grpc::ClientContext* context, const ::brad::EndSessionRequest* request, ::brad::EndSessionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_EndSession_, context, request, response, reactor);
}

void Brad::Stub::experimental_async::EndSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::brad::EndSessionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_EndSession_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::brad::EndSessionResponse>* Brad::Stub::AsyncEndSessionRaw(::grpc::ClientContext* context, const ::brad::EndSessionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::brad::EndSessionResponse>::Create(channel_.get(), cq, rpcmethod_EndSession_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::brad::EndSessionResponse>* Brad::Stub::PrepareAsyncEndSessionRaw(::grpc::ClientContext* context, const ::brad::EndSessionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::brad::EndSessionResponse>::Create(channel_.get(), cq, rpcmethod_EndSession_, context, request, false);
}

Brad::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Brad_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Brad::Service, ::brad::StartSessionRequest, ::brad::StartSessionResponse>(
          [](Brad::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::brad::StartSessionRequest* req,
             ::brad::StartSessionResponse* resp) {
               return service->StartSession(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Brad_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Brad::Service, ::brad::RunQueryRequest, ::brad::RunQueryResponse>(
          [](Brad::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::brad::RunQueryRequest* req,
             ::grpc_impl::ServerWriter<::brad::RunQueryResponse>* writer) {
               return service->RunQuery(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Brad_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Brad::Service, ::brad::RunQueryRequest, ::brad::RunQueryJsonResponse>(
          [](Brad::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::brad::RunQueryRequest* req,
             ::brad::RunQueryJsonResponse* resp) {
               return service->RunQueryJson(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Brad_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Brad::Service, ::brad::EndSessionRequest, ::brad::EndSessionResponse>(
          [](Brad::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::brad::EndSessionRequest* req,
             ::brad::EndSessionResponse* resp) {
               return service->EndSession(ctx, req, resp);
             }, this)));
}

Brad::Service::~Service() {
}

::grpc::Status Brad::Service::StartSession(::grpc::ServerContext* context, const ::brad::StartSessionRequest* request, ::brad::StartSessionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Brad::Service::RunQuery(::grpc::ServerContext* context, const ::brad::RunQueryRequest* request, ::grpc::ServerWriter< ::brad::RunQueryResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Brad::Service::RunQueryJson(::grpc::ServerContext* context, const ::brad::RunQueryRequest* request, ::brad::RunQueryJsonResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Brad::Service::EndSession(::grpc::ServerContext* context, const ::brad::EndSessionRequest* request, ::brad::EndSessionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace brad

