# NOTE: These are sample values. Create a copy of this file and replace the
# values with your own credentials where needed.

# **DO NOT** check in your config.yml file!

server_interface: "0.0.0.0"
server_port: 6583
server_daemon_port: 6586

# BRAD uses these credentials when interacting with the AWS APIs.
# These credentials should have access to
# - Athena
# - RDS
# - Redshift
# - S3
aws_access_key: ABCABCABC123ABCABC45
aws_access_key_secret: abCD+E1f2Gxhi3J4klmN/OP5QrSTuvwXYzabcdEF

# BRAD stores metadata here (e.g., the physical data blueprint).
s3_metadata_bucket: geoffxy-research
s3_metadata_path: iohtap/metadata/

# Holds intermediate results during data syncing.
s3_extract_bucket: your-bucket
s3_extract_path: extract/path/
s3_extract_region: us-east-1

# Set to a non-zero value enable automatic data syncing. When this is set to 0,
# automatic syncing is disabled.
data_sync_period_seconds: 0

# Set to always_{aurora, athena, redshift} to force IOHTAP to route all queries
# to the specified engine. The `default` routing policy uses a predictor to
# select the most suitable engine.
routing_policy: default

athena:
  odbc_driver: Athena
  aws_region: us-east-1
  s3_output_path: s3://your-bucket/output/path
  s3_data_path: s3://your-bucket/data/path
  access_key: ABCABCABC123ABCABC45
  access_key_secret: abCD+E1f2Gxhi3J4klmN/OP5QrSTuvwXYzabcdEF

aurora:
  odbc_driver: PostgreSQL
  host: aurora.us-east-1.amazonaws.com
  port: 5432
  user: postgres
  password: postgres_password

redshift:
  odbc_driver: Redshift
  host: redshift.us-east-1.amazonaws.com
  port: 5439
  user: awsuser
  password: awsuser_password
  s3_iam_role: arn:aws:iam:123
