strategy: query_based_beam

# Used to specify the period of time over which to use data for planning.
# Currrently, this is a "look behind" window for the workload.
planning_window:
  weeks: 0
  days: 0
  hours: 0
  minutes: 5

# Each second in the previous workload is treated as 10 seconds (so a 5 min
# planning window is treated as 50 mins). This is to make scenario run times
# more managable.
reinterpret_second_as: 10

# The query distribution must change by at least this much for a new blueprint
# to be accepted.
query_dist_change_frac: 0.1

###
### Trigger configs.
###

triggers:
  enabled: true
  check_period_s: 60  # Triggers are checked every X seconds.
  check_period_offset_s: 20

  elapsed_time:
    disabled: true
    multiplier: 60  # Multiplier over `planning_window`.

  redshift_cpu:
    lo: 10
    hi: 90
    sustained_epochs: 3

  aurora_cpu:
    lo: 10
    hi: 85
    sustained_epochs: 3

  variable_costs:
    threshold: 0.5

  query_latency_ceiling:
    ceiling_s: 30.0
    sustained_epochs: 3

###
### Beam planning constants.
###

beam_size: 100
max_provisioning_multiplier: 3
max_feasible_cpu: 85


###
### Neighborhood blueprint planning constants.
###

max_num_table_moves: 3

# Used by the "sampled_neighborhood" strategy
sample_set_size: 100000


###
### Transition and operational cost constants.
###

# $5.00 per TB of data scanned.
# There is a minimum charge of 10 MB.
athena_usd_per_mb_scanned: 0.000005
athena_min_mb_per_query: 10

# 1 I/O operation per 8 KB page.
# $0.20 per 1 million I/O operations.
aurora_usd_per_million_ios: 0.20

# Assumption is a fixed time cost for a provisioning change.
# The provisioning change time likely is a function of the instance types being
# changed, number of nodes being added/removed, and amount of data stored.
redshift_provisioning_change_time_s: 60
aurora_provisioning_change_time_s: 60

aurora_per_instance_change_time_s: 300  # 5 minutes
redshift_elastic_resize_time_s: 900  # 15 minutes - https://repost.aws/knowledge-center/resize-redshift-cluster
redshift_classic_resize_time_s: 7200  # 2 hours (This is very difficult to estimate; it depends on state we have no visibility into.)

redshift_extract_rate_mb_per_s: 10.0
redshift_load_rate_mb_per_s: 10.0

aurora_extract_rate_mb_per_s: 10.0
aurora_load_rate_mb_per_s: 10.0

# Extracting / loading in Athena corresponds to a conversion to/from Iceberg.
athena_extract_rate_mb_per_s: 10.0
athena_load_rate_mb_per_s: 10.0

s3_usd_per_mb_per_month: 0.000023

###
### Dataset-specific Transition Constants
###

# Use tools/calibration/table_sizes.py
table_extract_bytes_per_row:
  imdb:
    aka_name: 82.32090609799353
    aka_title: 115.56655840563032
    cast_info: 42.24659189517344
    char_name: 72.90391741131415
    comp_cast_type: 11.25
    company_name: 78.17681702901008
    company_type: 23.0
    complete_cast: 17.87376189982678
    info_type: 17.061946902654867
    keyword: 29.722837823099574
    kind_type: 12.142857142857142
    link_type: 14.5
    movie_companies: 38.37564715243578
    movie_info_idx: 27.599008162123223
    movie_keyword: 20.829555089708155
    movie_link: 21.888322165549887
    name: 79.93293378151274
    role_type: 13.333333333333334
    title: 90.16314998231906
    movie_info: 73.69504549846432
    person_info: 133.59130584387262

  imdb_extended:
    theatres: 30.569
    showings: 47.33581266922088
    ticket_orders: 41.52476844359898
    aka_name: 82.09059925022993
    aka_title: 115.82265016377478
    cast_info: 42.755255854541055
    char_name: 72.92298283720325
    comp_cast_type: 11.25
    company_name: 78.13220594305459
    company_type: 23.0
    complete_cast: 17.87376189982678
    info_type: 17.061946902654867
    keyword: 28.256227174480138
    kind_type: 12.142857142857142
    link_type: 14.5
    movie_companies: 36.64833781694964
    movie_info_idx: 27.52364903788672
    movie_keyword: 20.734031472635518
    movie_link: 21.888322165549887
    name: 79.88613316741416
    role_type: 13.333333333333334
    title: 90.15402727195061
    movie_info: 66.48728137225561
    person_info: 133.20102076348735

  imdb_extended_20g:
    homes: 20.556198
    theatres: 32.4135
    showings: 46.01808
    ticket_orders: 36.773404
    aka_name: 81.795698
    aka_title: 115.56834554266997
    cast_info: 35.296638
    char_name: 71.25104
    comp_cast_type: 11.25
    company_name: 78.345222
    company_type: 23.0
    complete_cast: 17.87376189982678
    info_type: 17.061946902654867
    keyword: 28.256227174480138
    kind_type: 12.142857142857142
    link_type: 14.5
    movie_companies: 42.636226
    movie_info_idx: 26.61975
    movie_keyword: 18.729882
    movie_link: 21.888322165549887
    name: 78.5697
    role_type: 13.333333333333334
    title: 88.5209
    movie_info: 29.449154
    person_info: 133.458044


###
### [Deprecated]
### Performance metrics scaling modifiers.
### (Used by neighborhood planning.)
###

dataset_scaling:
  redshift_CPUUtilization_Average: 1.0
  redshift_ReadIOPS_Average: 1.0
  aurora_WRITER_CPUUtilization_Average: 1.0
  aurora_WRITER_ReadIOPS_Average: 1.0
  aurora_WRITER_WriteIOPS_Average: 1.0
  athena_TotalExecutionTime_Sum: 1.0

redshift_resource_scaling:
  redshift_CPUUtilization_Average: 1.0
  redshift_ReadIOPS_Average: 1.0

aurora_resource_scaling:
  aurora_WRITER_CPUUtilization_Average: 1.0
  aurora_WRITER_ReadIOPS_Average: 1.0
  aurora_WRITER_WriteIOPS_Average: 1.0

# [Deprecated]
# Legacy Aurora scan cost estimator.
# $0.000025 per MB scanned.
aurora_usd_per_mb_scanned: 0.000025

###
### [Deprecated]
### Query latency scaling modifiers (across provisionings).
###

aurora_alpha: 0.97066455
aurora_gamma: 0.722149076

redshift_alpha: 0.7857837
redshift_gamma: 0.635405229


###
### [Deprecated]
### Load factor scaling modifiers.
###

redshift_load_factor:
  resource_alpha: 0.753694931989888
  # p = [alpha * base * gamma * CPU] + [(1 - gamma) * base]
  cpu_alpha: 0.04322972
  cpu_gamma: 0.500017

  # Legacy factors.
  cpu_to_load_alpha: 0.7861541
  min_scaling_cpu: 30

# [Deprecated]
aurora_load_factor:
  # Proportionality factor for cross-provisioning CPU changes.
  resource_alpha: 1.0

  # Proportionality factor for the load metric's effect on query latency.
  # p = alpha * base * load
  load_alpha: 0.53865956

  # Legacy factors.
  cpu_to_load_alpha: 0.8761541
  min_scaling_cpu: 30


###
### Transactional workload modifiers.
###

aurora_txns:
  # N.B. These values are for the initial IMDB "bulk insert" transactions
  client_thpt_to_load: 0.06493011
  client_thpt_to_cpu_denorm: 0.04584762
  # We used the number of CPUs as the "resource score".
  # Should be a bit more precise.
  prov_to_peak_cpu_denorm: 0.56730588

  # N.B. These values are for the IMDB-extended transactions.
  client_thpt_to_cpu_denorm: 0.0015366357203185784
  client_thpt_to_load: 0.0037392906617191367
  # We used the number of CPUs as the "resource score".
  # Should be a bit more precise.
  prov_to_peak_cpu_denorm: 0.6800294117647058

  imdb_extended_20g:
    K_l: 0.874
    b_p50: 0.00629548
    b_p90: 0.00629548  # TODO: Adjust


aurora_scaling:
  # [coef1(load)^2(resource ratio)^2 + coef2(load)^2 + coef3(resource ratio)^2 + coef4] * base
  coef1: 0.2454489
  coef2: 0.00841046
  coef3: 0.27845245
  coef4: 0.56823644

redshift_scaling:
  # Same model as above.
  # [coef1(load)^2(resource ratio)^2 + coef2(load)^2 + coef3(resource ratio)^2 + coef4] * base
  # Load is denormalized CPU usage.
  coef1: 0.63933825
  coef2: 0.00370447
  coef3: 0.49948713
  coef4: 0.36256359

use_io_optimized_aurora: true
