strategy: neighborhood

max_num_table_moves: 5
max_provisioning_multiplier: 3

# $5.00 per TB of data scanned.
# Technically, there is a minimum charge of 10 MB.
athena_usd_per_mb_scanned: 0.000005

# 1 I/O operation per 8 KB page.
# $0.20 per 1 million I/O operations.
# $0.000025 per MB scanned.
aurora_usd_per_mb_scanned: 0.000025

# Assumption is a fixed time cost for a provisioning change.
# The provisioning change time likely is a function of the instance types being
# changed, number of nodes being added/removed, and amount of data stored.
redshift_provisioning_change_time_s: 60
aurora_provisioning_change_time_s: 60

redshift_extract_rate_mb_per_s: 10.0
redshift_load_rate_mb_per_s: 10.0

aurora_extract_rate_mb_per_s: 10.0
aurora_load_rate_mb_per_s: 10.0

# Extracting / loading in Athena corresponds to a conversion to/from Iceberg.
athena_extract_rate_mb_per_s: 10.0
athena_load_rate_mb_per_s: 10.0
