strategy: query_based_beam

###
### Beam planning constants.
###

beam_size: 100
max_provisioning_multiplier: 3
max_feasible_cpu: 85


###
### Neighborhood blueprint planning constants.
###

max_num_table_moves: 3

# Used by the "sampled_neighborhood" strategy
sample_set_size: 100000


###
### Transition and operational cost constants.
###

# $5.00 per TB of data scanned.
# There is a minimum charge of 10 MB.
athena_usd_per_mb_scanned: 0.000005
athena_min_mb_per_query: 10

# 1 I/O operation per 8 KB page.
# $0.20 per 1 million I/O operations.
aurora_usd_per_million_ios: 0.20

# Assumption is a fixed time cost for a provisioning change.
# The provisioning change time likely is a function of the instance types being
# changed, number of nodes being added/removed, and amount of data stored.
redshift_provisioning_change_time_s: 60
aurora_provisioning_change_time_s: 60

redshift_extract_rate_mb_per_s: 10.0
redshift_load_rate_mb_per_s: 10.0

aurora_extract_rate_mb_per_s: 10.0
aurora_load_rate_mb_per_s: 10.0

# Extracting / loading in Athena corresponds to a conversion to/from Iceberg.
athena_extract_rate_mb_per_s: 10.0
athena_load_rate_mb_per_s: 10.0

s3_usd_per_mb_per_month: 0.000023

###
### Dataset-specific Transition Constants
###

# Use tools/calibration/table_sizes.py
table_extract_bytes_per_row:
  imdb:
    aka_name: 82.32090609799353
    aka_title: 115.56655840563032
    cast_info: 42.24659189517344
    char_name: 72.90391741131415
    comp_cast_type: 11.25
    company_name: 78.17681702901008
    company_type: 23.0
    complete_cast: 17.87376189982678
    info_type: 17.061946902654867
    keyword: 29.722837823099574
    kind_type: 12.142857142857142
    link_type: 14.5
    movie_companies: 38.37564715243578
    movie_info_idx: 27.599008162123223
    movie_keyword: 20.829555089708155
    movie_link: 21.888322165549887
    name: 79.93293378151274
    role_type: 13.333333333333334
    title: 90.16314998231906
    movie_info: 73.69504549846432
    person_info: 133.59130584387262


###
### Performance metrics scaling modifiers.
### (Used by neighborhood planning.)
###

dataset_scaling:
  redshift_CPUUtilization_Average: 1.0
  redshift_ReadIOPS_Average: 1.0
  aurora_WRITER_CPUUtilization_Average: 1.0
  aurora_WRITER_ReadIOPS_Average: 1.0
  aurora_WRITER_WriteIOPS_Average: 1.0
  athena_TotalExecutionTime_Sum: 1.0

redshift_resource_scaling:
  redshift_CPUUtilization_Average: 1.0
  redshift_ReadIOPS_Average: 1.0

aurora_resource_scaling:
  aurora_WRITER_CPUUtilization_Average: 1.0
  aurora_WRITER_ReadIOPS_Average: 1.0
  aurora_WRITER_WriteIOPS_Average: 1.0

# Legacy Aurora scan cost estimator.
# $0.000025 per MB scanned.
aurora_usd_per_mb_scanned: 0.000025

###
### Query latency scaling modifiers (across provisionings).
###

aurora_alpha: 0.97066455
aurora_gamma: 0.722149076

redshift_alpha: 0.7857837
redshift_gamma: 0.635405229


###
### Load factor scaling modifiers.
###

redshift_load_factor:
  resource_alpha: 0.753694931989888
  # p = [alpha * base * gamma * CPU] + [(1 - gamma) * base]
  cpu_alpha: 0.04322972
  cpu_gamma: 0.500017

  # Legacy factors.
  cpu_to_load_alpha: 0.7861541
  min_scaling_cpu: 30

# TODO: These are Redshift values.
aurora_load_factor:
  resource_alpha: 0.753694931989888
  cpu_to_load_alpha: 0.8761541
  min_scaling_cpu: 30
