query_latency_p90_ceiling_s: 30.0
txn_latency_p50_ceiling_s: 0.020  # Currently unused.
txn_latency_p90_ceiling_s: 0.030

comparator:
  type: perf_ceiling  # or `benefit_perf_ceiling`

  benefit_horizon:  # Only used by the `benefit_perf_ceiling` comparator
    weeks: 0
    days: 0
    hours: 1
    minutes: 0

  penalty_threshold: 0.8  # Only used by the `benefit_perf_ceiling` comparator

# Use this instead of the individual paths below.
std_datasets:
  - name: regular
    path: workloads/IMDB_100GB/regular_test/
  - name: adhoc
    path: workloads/IMDB_100GB/adhoc_test/

# The configurations below are deprecated. Do not use them in new experiment
# code (they don't need to be included either).

std_dataset_path: workloads/IMDB_20GB/regular_test/

aurora_preds_path: workloads/IMDB/OLAP_queries_new/pred_aurora_300.npy
redshift_preds_path: workloads/IMDB/OLAP_queries_new/pred_redshift_300.npy
athena_preds_path: workloads/IMDB/OLAP_queries_new/pred_athena_300.npy

aurora_data_access_path: workloads/IMDB/OLAP_queries_new/pred_aurora_blocks_300.npy
athena_data_access_path: workloads/IMDB/OLAP_queries_new/pred_athena_bytes_scanned_300.npy

query_bank_path: workloads/IMDB/OLAP_queries_new/all_queries_300.sql
