latency_ceiling_s: 30.0
txn_latency_p50_ceiling_s: 0.020  # Currently unused.
txn_latency_p90_ceiling_s: 0.030

# This is a new concept that we use to reconcile a blueprint's costs and
# transition times.
use_payoff_period: true

payoff_period:
  weeks: 0
  days: 0
  hours: 1
  minutes: 0

# This is used when the current blueprint is violating performance constraints
# (due to a changed workload) and we want to transition quickly to a better
# blueprint. The larger this value, the more we prefer higher cost but faster to
# transition to blueprints. Units are in $/hour.
payoff_penalty: 100.0

# Use this instead of the individual paths below.
std_dataset_path: workloads/IMDB_20GB/regular_test/

# The configurations below are deprecated. Do not use them in new experiment
# code (they don't need to be included either).

aurora_preds_path: workloads/IMDB/OLAP_queries_new/pred_aurora_300.npy
redshift_preds_path: workloads/IMDB/OLAP_queries_new/pred_redshift_300.npy
athena_preds_path: workloads/IMDB/OLAP_queries_new/pred_athena_300.npy

aurora_data_access_path: workloads/IMDB/OLAP_queries_new/pred_aurora_blocks_300.npy
athena_data_access_path: workloads/IMDB/OLAP_queries_new/pred_athena_bytes_scanned_300.npy

query_bank_path: workloads/IMDB/OLAP_queries_new/all_queries_300.sql
