CLOUDWATCH_LOAD_METRICS = [
    ("CPUUtilization", "Minimum"),
    ("CPUUtilization", "Maximum"),
    ("CPUUtilization", "Average"),
    ("ReadIOPS", "Minimum"),
    ("ReadIOPS", "Maximum"),
    ("ReadIOPS", "Average"),
    ("WriteIOPS", "Minimum"),
    ("WriteIOPS", "Maximum"),
    ("WriteIOPS", "Average"),
    ("ReadThroughput", "Minimum"),
    ("ReadThroughput", "Maximum"),
    ("ReadThroughput", "Average"),
    ("WriteThroughput", "Minimum"),
    ("WriteThroughput", "Maximum"),
    ("WriteThroughput", "Average"),
    ("ReadLatency", "Minimum"),
    ("ReadLatency", "Maximum"),
    ("ReadLatency", "Average"),
    ("WriteLatency", "Minimum"),
    ("WriteLatency", "Maximum"),
    ("WriteLatency", "Average"),
]

PERF_INSIGHTS_LOAD_METRICS = [
    "os.loadAverageMinute.one",
    "os.loadAverageMinute.five",
    "os.loadAverageMinute.fifteen",
    "os.cpuUtilization.system",
    "os.cpuUtilization.total",
    "os.cpuUtilization.user",
    "os.diskIO.avgQueueLen",
    "os.diskIO.tps",
    "os.diskIO.util",
    "os.diskIO.readIOsPS",
    "os.diskIO.readKbPS",
    "os.diskIO.writeIOsPS",
    "os.diskIO.writeKbPS",
    "os.network.rx",
    "os.network.tx",
    "os.memory.active",
    "os.memory.dirty",
    "os.memory.free",
    "os.memory.writeback",
    "os.memory.total",
    "os.tasks.blocked",
    "os.tasks.running",
    "os.tasks.sleeping",
    "os.tasks.stopped",
    "os.tasks.total",
    "db.SQL.queries",
    "db.SQL.total_query_time",
    "db.SQL.tup_deleted",
    "db.SQL.tup_fetched",
    "db.SQL.tup_inserted",
    "db.SQL.tup_returned",
    "db.SQL.tup_updated",
    "db.Transactions.active_transactions",
    "db.Transactions.blocked_transactions",
    "db.Transactions.duration_commits",
    "db.Transactions.xact_commit",
    "db.Transactions.xact_rollback",
    # NOTE: Aurora has specific storage metrics (probably because they use a custom storage engine)
    # https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_PerfInsights_Counters.html#USER_PerfInsights_Counters.Aurora_PostgreSQL
    "os.diskIO.auroraStorage.auroraStorageBytesRx",
    "os.diskIO.auroraStorage.auroraStorageBytesTx",
    "os.diskIO.auroraStorage.diskQueueDepth",
    "os.diskIO.auroraStorage.readThroughput",
    "os.diskIO.auroraStorage.writeThroughput",
    "os.diskIO.auroraStorage.readLatency",
    "os.diskIO.auroraStorage.writeLatency",
    "os.diskIO.auroraStorage.readIOsPS",
    "os.diskIO.auroraStorage.writeIOsPS",
]
