# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interface.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from brad.proto_gen.interface import blueprint_pb2 as interface_dot_blueprint__pb2
from brad.proto_gen.interface import schema_pb2 as interface_dot_schema__pb2
from brad.proto_gen.interface import vdbe_pb2 as interface_dot_vdbe__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finterface.proto\x12\x04vdbe\x1a\x19interface/blueprint.proto\x1a\x16interface/schema.proto\x1a\x14interface/vdbe.proto\"\x87\x01\n\x0bSystemState\x12\x13\n\x0bschema_name\x18\x01 \x01(\t\x12\x1b\n\x06tables\x18\x02 \x03(\x0b\x32\x0b.vdbe.Table\x12\"\n\x05vdbes\x18\x03 \x03(\x0b\x32\x13.vdbe.VirtualEngine\x12\"\n\tblueprint\x18\x04 \x01(\x0b\x32\x0f.vdbe.Blueprintb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interface_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SYSTEMSTATE']._serialized_start=99
  _globals['_SYSTEMSTATE']._serialized_end=234
# @@protoc_insertion_point(module_scope)
